### ISSUE TITLE
npm outdated should scold old ssau versions.

### ISSUE THREAD

**Issue by gregglind** [pdehaan/shield-linter#17]

**Comment by pdehaan** [comment]
I have [this test](https://github.com/pdehaan/shield-linter/blob/master/rules/package/addon-utils.js) which sees if you have at least **shield-studies-addon-utils@5.0.0**.
We could probably try and do a check on npm to see what the latest published version is, and nag people if they're off by a patch/minor version as well.

**Comment by pdehaan** [comment]
This was the module I was trying to remember: https://github.com/sindresorhus/latest-version
I can try poking at it today and see if I can compare the shield study’s current pinned/semver version number with the latest published version number on npm.

**Comment by pdehaan** [comment]
@gregglind Yeah, you can also use <kbd>$ npm info shield-studies-addon-utils version # 5.0.3</kbd> to just extract the `version` property too, but then I'd have to use [`child_process.execSync()`](https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options) or something.

I was thinking I could also just include `"shield-studies-addon-utils": "latest"` in the **shield-linter**'s package.json, and then do something "clever" like this:

```js
const {version} = require("shield-studies-addon-utils/package.json");
console.log(version); // "5.0.3"
```

But not sure if npx and npm would _always_ resolve and download the latest version, or if package-lock.json would try and pin the version number or what. Plus, it feels like it's being too clever and turns out being hacky and using `child_process.exec()` or **latest-version** or something similar would be smarter.

**Comment by pdehaan** [comment]
In fact, here's the magic:

```js
// A: Include **shield-studies-addon-utils** module in package.json, and query it's package.json directly.
const {version} = require("shield-studies-addon-utils/package.json");
console.log(version); // "5.0.3"

// B: Use **latest-version** module which queries npm directly.
const latestVersion = require('latest-version');
latestVersion('shield-studies-addon-utils').then(console.log); // "5.0.3"

// C: Use built-in `child_process.execSync()` to invoke `npm info ...`.
const {execSync} = require("child_process");
const data = execSync("npm info shield-studies-addon-utils version", {encoding: "utf-8"});
console.log(data.trim()); // "5.0.3"
```

**Comment by pdehaan** [comment]
I went with the `execSync()` approach here:

https://github.com/pdehaan/shield-linter/blob/e01d7bc43447b64c49832c9b7a9c5750e9ffda2b/rules/package/addon-utils.js#L50-L53

Here's the current output for a slightly modified federated-learning-addon Add-on (where I downgraded the package.json's version number to 5.0.2 so it was outdated):

> Please install the latest version of "shield-studies-addon-utils". Current: 5.0.2. Latest: 5.0.3

```sh
➜  federated-learning-addon git:(master) $ git rev-parse --short HEAD # 4749760
➜  federated-learning-addon git:(master) $ npx pdehaan/shield-linter -m ./manifest.json -p ./package.json
npx: installed 49 in 5.373s
[package.json:rules/package/addon-utils] Please install the latest version of "shield-studies-addon-utils". Current: 5.0.2. Latest: 5.0.3
[package.json:rules/package/ci] Missing Travis or Circle CI configs
[package.json:rules/package/eslint] federated-learning-addon shield study is not using "eslint" package
[package.json:rules/package/eslint] federated-learning-addon shield study is not using "eslint-plugin-mozilla" package
[package.json:rules/package/license] Does not include a "license" property
```
