### ISSUE TITLE
scold about no CI integrations.

### ISSUE THREAD

**Issue by gregglind** [pdehaan/shield-linter#18]

**Comment by pdehaan** [comment]
This could be a bit tricky. I run certain checks based on if you specify a `--manifest-path` or `--package-path` flag via the CLI. So if a user specifies a package.json file to check, I could look for a ".travis.yml" in the same directory (since we generally assume package.json files are in the root of a project). Similarly, we could check the same directory for a "circle.yml" file or ".circleci" directory.

**Comment by pdehaan** [comment]
Fixed via #20.
